### ISSUE TITLE
LaTeX to HTML failing to terminate `\emph{...}` properly

### ISSUE THREAD

**Issue by Iiridayn** [ssavitzky/MakeStuff#2]
See, ie, the bottom of https://steve.savitzky.net/Songs/lad/, line: "Also note that I'm about 10 years older than Frank Hayes, so I don't _have} to exaggerate_."

Could instead be a generated/cached file which wasn't updated after fixing whatever bug caused it.

**Comment by ssavitzky** [comment]
Thanks! Most likely a case I missed; the LaTeX-to-HTML conversion is done in [MakeStuff/flktran.pl](https://github.com/ssavitzky/MakeStuff/blob/master/TeX/flktran.pl), which dates back to 1998 and has moss growing in some places.

**Comment by ssavitzky** [comment]
Actually the problem was an {\em ...} split across a line break, which my incredibly stupid converter doesn't handle yet.  But I wasn't handling \emph{...} (or the local tag \spoken...{}) at all, so [f54ccb3](https://github.com/ssavitzky/MakeStuff/commit/f54ccb35902d55aa7aee9dda12132440c99886f6) fixes those as well.
